version: "2"

linters:
  default: all
  disable:
    - cyclop
    - decorder
    - depguard
    - dupword
    - err113
    - errchkjson
    - errcheck
    - exhaustruct
    - exhaustruct_v5
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecksumtype
    - gochecknoglobals # TODO
    - gocognit
    - goconst
    - gocyclo
    - godoclint
    - godox
    - goheader
    - gomodguard
    - grouper
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - noinlineerr
    - nakedret
    - nlreturn
    - nonamedreturns
    - spancheck
    - testpackage
    - unqueryvet
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint

  settings:
    funcorder:
      constructor: true
      struct-method: false
      alphabetical: false

    revive:
      rules:
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#package-comments
        - name: package-comments
          disabled: true
        # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#unchecked-type-assertion
        - name: unchecked-type-assertion
          arguments:
            - accept-ignored-assertion-result: true
    wsl_v5:
      disable:
        - append
        - assign
        - assign-exclusive
        - assign-expr
        - defer
        - err
        - expr
        - return
        - trailing-whitespace

  exclusions:
    warn-unused: true
    generated: strict
    rules:
      - text: "^[a-z].+?\\s" # allow private globals
        linters:
          - gochecknoglobals
      - text: "local replacement are not allowed: github.com/heffcodex/the"
        linters:
           - gomoddirectives

    paths: []

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true
  new: false
  fix: false

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

  sort-order:
    - linter
    - file
    - severity

  show-stats: false

run:
  timeout: 5m
  relative-path-mode: gomod
  issues-exit-code: 1
  tests: true
  build-tags: []
  modules-download-mode: readonly
  allow-parallel-runners: false
  allow-serial-runners: false

severity:
  default: "@linter"
  rules: []
